version: "3.4"

services:  
        redis:
                image: redis:latest
                hostname: redis

        web:
                build:
                        context: .
                        dockerfile: Cloud_dockerfile
                        target: calcus_user
                restart: always
                hostname: web
                user: "${UID}:${GID}"
                command: ./scripts/run_web.sh
                expose:
                        - 8000
                volumes:
                        - .:/calcus/
                        - ./scr:/calcus/scr
                        - ./keys:/calcus/keys
                        - ./backups:/calcus/backups
                        - ./logs:/calcus/logs
                        - ./frontend:/calcus/frontend
                links:
                        - redis
                env_file:
                        - ./.env
                depends_on:
                        - postgres
                environment:
                        - GUNICORN_TIMEOUT=30
                        - CALCUS_DEBUG=True
                        - ACTIONS_HOST_URL=http://web:8000
                        - COMPUTE_SMALL_HOST_URL=http://cloud-compute:8001
                        - COMPUTE_MEDIUM_HOST_URL=http://cloud-compute:8001
                        - COMPUTE_LARGE_HOST_URL=http://cloud-compute:8001
                        - GCP_LOCATION=us-central1
                        - GCP_PROJECT_ID=test-project
                        - GCP_SERVICE_ACCOUNT_EMAIL=selenium@calcus.com

        nginx:
                image: nginx:latest
                ports:
                        - "8080:8080"
                volumes:
                        - ./docker/nginx/:/etc/nginx/conf.d
                        - ./static:/static
                        - .:/calcus
                depends_on: 
                        - web        
        taskqueue:
              image: raphaelrobidas/cloud-tasks-emulator:latest
              environment:
                    QUEUE_HOST: taskqueue # should be "localhost" for Github actions
                    QUEUE_PORT: 8123
                    QUEUE_NAME: projects/test-project/locations/us-central1/queues/xtb-compute,projects/test-project/locations/us-central1/queues/actions,projects/test-project/locations/us-central1/queues/analytics
              expose:
                    - 8123
              depends_on:
                    - web
        cloud-compute:
                build:
                        context: .
                        dockerfile: Cloud_dockerfile
                hostname: cloud-compute
                user: "${UID}:${GID}"
                expose:
                        - 8001
                depends_on:
                        - redis
                volumes:
                        - ./scr:/calcus/scr
                        - ./keys:/calcus/keys
                        - ./backups:/calcus/backups
                        - ./logs:/calcus/logs
                        - ./frontend:/calcus/frontend

                env_file:
                        - ./.env
                environment:
                        - CALCUS_DEBUG=True
                        - CALCUS_CLOUD=True
                        - CALCUS_TEST=True
                        - NUM_THREADS=4
                        - NUM_WORKERS=1
                        - PORT=8001
                        - GCP_LOCATION=us-central1
                        - GCP_PROJECT_ID=test-project
                        - GCP_SERVICE_ACCOUNT_EMAIL=selenium@calcus.com
                        - ACTIONS_HOST_URL=http://web:8000
                        - COMPUTE_SMALL_HOST_URL=http://cloud-compute:8001
                        - COMPUTE_MEDIUM_HOST_URL=http://cloud-compute:8001
                        - COMPUTE_LARGE_HOST_URL=http://cloud-compute:8001
                        - CALCUS_SCR_HOME=/calcus/scr
                        - CALCUS_TEST_SCR_HOME=/calcus/scr
                        - GUNICORN_TIMEOUT=15

        postgres:
                image: postgres:11-bullseye
                restart: always
                user: "${UID}:${GID}"
                volumes:
                        - ./data:/var/lib/postgresql/data/:rw
                        - ./docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
                        - ./backups:/calcus/backups
                        - ./logs:/calcus/logs
                env_file:
                        - ./.env
                environment:
                        - PGDATA=/var/lib/postgresql/data/
                        - POSTGRES_USER=calcus
                        - POSTGRES_DB=calcus

volumes:
  scratch:
